APP = docker-gradle
TAG= jdk8-gradle-4.2
include $(MAKEPATH)/Makefile

marathon:
	@echo no-op

compile:
	@echo no-op

marathon_app:
	@echo no-op

marathon_base:
	@echo no-op

launcher_app:
	@echo no-op
