# App Ids
CASSANDRA_APP_ID = /$(GROUP)/$(ENV)/cassandra
LOGGER_CASSANDRA_APP_ID = /$(GROUP)/$(ENV)/log/cassandra
REDIS_APP_ID = /$(GROUP)/$(ENV)/redis
CASSANDRA_STORAGE_APP_ID = /$(GROUP)/$(ENV)/cassandrastorage
LOGGER_CASSANDRA_STORAGE_APP_ID = /$(GROUP)/$(ENV)/log/cassandrastorage
KAFKA_APP_ID= /$(GROUP)/$(ENV)/kafka

DEAFULT_MIN_CPUS = -1

# Cassandra proto and CQL versions
CASSANDRA_PROTO_VERSION ?= 4
CASSANDRA_CQL_VERSION ?= 3.4.2

# Tags
FILESERVER_TAG = 0.5
CASSANDRA_TAG = cassandra:3.11.1
KAFKA_TAG = 0.10.1.0-r0.1-l0.3-2.4
ZOOKEEPER_TAG = 3.4.6-r1.6-l0.3-2.4

# Logging
ENABLE_DEBUG = false
DKT_LOGGER_IS_KAFKA_ENABLED = true
DKT_LOGGER_DUMP_MSG_STDOUT = false

# Mesos
MESOS_MASTER_HOST_PORT = master.mesos:5050
MESOS_ZK_HOST_PORT = zk-1.zk:2181,zk-2.zk:2181,zk-3.zk:2181,zk-4.zk:2181,zk-5.zk:2181

# Kafka ZK
KAFKA_CLUSTER_NODES = 5
KAFKA_CLUSTER_RF = 2
KAFKA_ZK_PATH = ""
NUM_PARTITIONS = 1

# Redis
REDIS_CLUSTER_NODES = 3
REDIS_CLUSTER_RF = 1

# ZK
ZOOKEEPER_CLUSTER_NODES = 5

# Cassandra
CASSANDRA_CLUSTER_NODES = 5
CASSANDRA_CLUSTER_SEED_NODES = 3
CASSANDRA_CLUSTER_RF = 3

# RTE
RTE_SERVICE_NAME = rte
RTE_LUA_CTRL_TOPIC = rte-lua-ctrl

# RTE modules
ENABLE_HTTP = false
ENABLE_NSQL = false
ENABLE_NSFTP = false
ENABLE_NSSFTP = false
ENABLE_NSOBJECT = false
ENABLE_NSKV = false
ENABLE_NSSTREAM = false
ENABLE_NSOUTPUT = true
ENABLE_TS = true
ENABLE_TS_NOTIFICATION = true

#portal nginx
PORTALNGINX_SERVICENAME ?= "Unused"
PORTALNGINX_EXTNETNAME ?= "Unused"
PORTALNGINX_EXTADDR ?= "Unused"

# SSL fix
TLS_SKIP_VERIFICATION = false

# Portal nginx cert
SSL_KEY_FILE ?= key.pem
SSL_CERT_FILE ?= cert.pem

# Northstar nginx cert
NORTHSTAR_NGINX_SSL_KEY_FILE ?= key.pem
NORTHSTAR_NGINX_SSL_CERT_FILE ?= cert.pem

#Northstar API
NORTHSTARAPI_MAX_ARG_COUNT = 10
NORTHSTARAPI_MAX_TIMEOUT = 360
NORTHSTARAPI_MAX_CODE_SIZE = 68916
NORTHSTARAPI_ENFORCE_CHECKSUM = false
NORTHSTARAPI_EXECUTION_MEMORY_MAX = 6000
NORTHSTARAPI_EXECUTION_MEMORY_DEFAULT = 1000

#NSSIM_TEST_GROUPS
NSSIM_TEST_GROUPS = "notebook_crud, template"

# NS sim
ITERATION_DELAY_IN_SEC = 5

# TS notification
NOTIFICATION_LIBRARY_VERSION="v2"
CLIENT_ID = "YourClientIDHere"
CLIENT_SECRET = "YourClientSecretHere"

# NGINX deployment control
USE_NORTHSTAR_NGINX=1
USE_PORTAL_NGINX=0
NGINX_BLOCK_ALLOW_FILE=devnet-allow.conf

USE_DPE_SPARK=false

#Elasticsearch config
USE_EKK_STACK = false
ELASTICSEARCH_MARATHON_APP_TMPL = marathon_app_ins.tmpl.json
ELASTICSEARCH_MARATHON_TARGET = marathon_ins.json
ELASTICSEARCH_CLUSTER_NODES = 5
ELASTICSEARCH_STORAGE_ENABLED = false
