# Portworx for DCOS and Marathon
PORTWORX = false
MARATHON_WITH_PORTWORX = false
DOCKER_USER = **ENTER VALID USER** 

# Native Cass, Kafka, and ZK
CASS_INS_APP = true
KAFKA_INS_APP = false
ZK_INS_APP = true
ZOOKEEPER_PORT = 0

# DCOS frameworks
DCOS_CASS_FRAMEWORK = false
DCOS_KAFKA_FRAMEWORK = false
DCOS_CASS_FRAMEWORK_USE_CUSTOM_ZK = false
DCOS_KAFKA_FRAMEWORK_USE_CUSTOM_ZK = false

# S3
BLOB_STORAGE_HOST_AND_PORT="127.0.0.1:9020"

# Logging
USE_COMMON_LOGGING_PIPELINE = 1
