USE_PROD_LOGGING = true
LOGGER_KAFKA_INS_APP = false
LOGGER_KAFKA_CLUSTER_NODES = 10
LOGGER_NUM_PARTITIONS = 20
LOGGER_KAFKA_CLUSTER_RF = 3
LOGGER_ZOOKEEPER_CLUSTER_NODES = 5

LOGGER_CASSANDRA_CLUSTER_NODES = 5
LOGGER_CASSANDRA_CLUSTER_RF = 3
LOGGER_CASS_INS_APP = true

REDIS_CLUSTER_NODES = 5
REDIS_CLUSTER_RF = 3

CASSANDRA_WITH_MLOGGER=true
