LOGGER_TAG=0.3-2.4
VAULTHELPER_TAG=0.0-0.1
FILESERVER_TAG=0.5
CASSANDRA_LAUNCHER_TAG=vz1.0.10
ZOOKEEPER_TAG=3.4.6-r1.6-l0.3-2.4
KAFKA_TAG=0.10.1.0-r0.4-l0.3-2.4
REDIS_TAG=3.2.9-r0.2-l0.3-2.7
CASSANDRA_TAG = dakota-cassandra:3.11-1.4
LOG_CASSANDRA_TAG = dakota-cassandra:3.11-1.4
LOGCONSUMER_TAG=0.4-3.6
CASSANDRAREST_TAG=0.4-3.0
JANITOR_TAG=vz0.2
STATS_INTERVAL=30
NUM_PARTITIONS = 2
MAX_MEMORY =1024.0
INFLUXDB_MEM = 16384
CASS_INS_APP = true
KAFKA_CONT_PATH = \/kafka-logs
ZK_CONT_PATH = \/zookeeper
CASS_CONT_PATH = \/var\/lib\/cassandra

LOGGER_KAFKA_CLUSTER_NODES = 10
LOGGER_ZOOKEEPER_CLUSTER_NODES = 5
LOGGER_NUM_PARTITIONS=20
LOGGER_KAFKA_CLUSTER_RF = 3
FORCE_PULL_IMAGE = true
DEPLOY_DELAY = 1
MON_PIPE_ID = tsx

REMOVE_DEAD_NODES=yes

DAKOTA_UBUNTU_LOGGER_IMAGE=dakota-ubuntu-logger
DAKOTA_LOGGER_IMAGE=dakota-logger
DAKOTA_VAULTHELPER_IMAGE=dakota-vaulthelper
DAKOTA_JAVA_LOGGER_IMAGE=dakota-java-logger
BASE_REGISTRY_HOST=docker.io
BASE_REGISTRY_PORT=

CASSANDRA_MEMTABLE_ALLOCATION_TYPE ?= "heap_buffers"

RESOURCE_ROLES=null

CURL_OPTS = --retry 5 --retry-delay 5 --connect-timeout 60

DKT_LOGGER_DUMP_MSG_STDOUT=false
DKT_LOGGER_IS_KAFKA_ENABLED=true
SEND_NOTIFICATION =false

